apiVersion: v1
kind: Namespace
metadata:
  name: autoscaling-demo
  labels:
    purpose: demo
    feature: autoscaling
---
# Deployment with Guaranteed QoS and HPA
# This demonstrates CPU-based horizontal scaling with guaranteed resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-guaranteed
  namespace: autoscaling-demo
  labels:
    app: frontend
    tier: guaranteed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: guaranteed
  template:
    metadata:
      labels:
        app: frontend
        tier: guaranteed
    spec:
      containers:
        - name: k8s-demo-app
          image: k8sdemoanbo.azurecr.io/k8s-demo-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RESOURCE_REQUEST_CPU
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: requests.cpu
            - name: RESOURCE_REQUEST_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: requests.memory
            - name: RESOURCE_LIMIT_CPU
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: limits.cpu
            - name: RESOURCE_LIMIT_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: limits.memory
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /health/startup
              port: http
            failureThreshold: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            periodSeconds: 10
---
# HPA for CPU-based horizontal scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-guaranteed-hpa
  namespace: autoscaling-demo
  labels:
    app: frontend
  annotations:
    demo.k8s/description: "HPA scales horizontally based on CPU utilization"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-guaranteed
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-guaranteed
  namespace: autoscaling-demo
spec:
  selector:
    app: frontend
    tier: guaranteed
  ports:
    - port: 80
      targetPort: http
  type: ClusterIP
