apiVersion: v1
kind: Namespace
metadata:
  name: vpa-demo
---
# Cleanup all VPA demo resources
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-demo-app-vpa
  namespace: vpa-demo
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-app-vpa
  namespace: vpa-demo
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-app-vpa
  namespace: vpa-demo
$patch: delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpa-demo
$patch: delete
