apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-demo-app-vpa
  namespace: vpa-demo
  labels:
    app: k8s-demo-app-vpa
  annotations:
    tutorial.k8s-demo/lesson: "04-vpa-auto-mode"
    tutorial.k8s-demo/description: "VPA in 'Auto' mode automatically adjusts resource requests and restarts pods when needed"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-demo-app-vpa
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: k8s-demo-app
        controlledResources:
          - cpu
          - memory
        minAllowed:
          cpu: "100m"
          memory: "128Mi"
        maxAllowed:
          cpu: "2"
          memory: "2Gi"
