apiVersion: v1
kind: Namespace
metadata:
  name: qos-demo
---
# Guaranteed QoS Class - requests == limits
# Highest priority, evicted last under memory pressure
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guaranteed-qos
  namespace: qos-demo
  labels:
    app: guaranteed-qos
    qos-class: guaranteed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guaranteed-qos
  template:
    metadata:
      labels:
        app: guaranteed-qos
        qos-class: guaranteed
    spec:
      containers:
        - name: k8s-demo-app
          image: k8sdemoanbo.azurecr.io/k8s-demo-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RESOURCE_REQUEST_CPU
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: requests.cpu
            - name: RESOURCE_REQUEST_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: requests.memory
            - name: RESOURCE_LIMIT_CPU
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: limits.cpu
            - name: RESOURCE_LIMIT_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: k8s-demo-app
                  resource: limits.memory
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health/startup
              port: http
            failureThreshold: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: guaranteed-qos
  namespace: qos-demo
  labels:
    app: guaranteed-qos
spec:
  selector:
    app: guaranteed-qos
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
